development:
  adapter: postgresql
  encoding: unicode
  database: mngdr_development
  pool: 5
  username: louy7
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: mngdr_test
  pool: 5
  username: louy7
  password: password1
